import { createSlice } from "@reduxjs/toolkit";

const employeesState = {
  list: [
    {
      id: 1,
      firstName: "Christina",
      lastName: "Leon",
      dateOfBirth: "1983-04-23",
      startDate: "2015-03-01",
      street: "3247 Hampton Meadows",
      city: "Haverhill",
      state: "MA",
      zipCode: "01830",
      department: "Sales",
    },
    {
      id: 2,
      firstName: "Richard",
      lastName: "Castillo",
      dateOfBirth: "1952-11-22",
      startDate: "2013-01-25",
      street: "4599 Hill Street",
      city: "Toledo",
      state: "OH",
      zipCode: "43609",
      department: "Marketing",
    },
    {
      id: 3,
      firstName: "Carl",
      lastName: "Sanders",
      dateOfBirth: "1953-10-20",
      startDate: "2015-11-02",
      street: "4225 Froe Street",
      city: "Wheeling",
      state: "WV",
      zipCode: "26003",
      department: "Engineering",
    },
    {
      id: 4,
      firstName: "Ethel",
      lastName: "Workman",
      dateOfBirth: "1988-06-20",
      startDate: "2014-03-17",
      street: "1622 Hummingbird Way",
      city: "Charlestown",
      state: "MA",
      zipCode: "02129",
      department: "Human Resources",
    },
    {
      id: 5,
      firstName: "John",
      lastName: "Roddy",
      dateOfBirth: "1976-03-01",
      startDate: "2014-04-03",
      street: "2737 Poe Lane",
      city: "Shawnee",
      state: "KS",
      zipCode: "66214",
      department: "Legal",
    },
    {
      id: 6,
      firstName: "Christina",
      lastName: "Leon",
      dateOfBirth: "1983-04-23",
      startDate: "2015-03-01",
      street: "3247 Hampton Meadows",
      city: "Haverhill",
      state: "MA",
      zipCode: "01830",
      department: "Sales",
    },
    {
      id: 7,
      firstName: "Richard",
      lastName: "Castillo",
      dateOfBirth: "1952-11-22",
      startDate: "2013-01-25",
      street: "4599 Hill Street",
      city: "Toledo",
      state: "OH",
      zipCode: "43609",
      department: "Marketing",
    },
    {
      id: 8,
      firstName: "Carl",
      lastName: "Sanders",
      dateOfBirth: "1953-10-20",
      startDate: "2015-11-02",
      street: "4225 Froe Street",
      city: "Wheeling",
      state: "WV",
      zipCode: "26003",
      department: "Engineering",
    },
    {
      id: 9,
      firstName: "Ethel",
      lastName: "Workman",
      dateOfBirth: "1988-06-20",
      startDate: "2014-03-17",
      street: "1622 Hummingbird Way",
      city: "Charlestown",
      state: "MA",
      zipCode: "02129",
      department: "Human Resources",
    },
    {
      id: 10,
      firstName: "John",
      lastName: "Roddy",
      dateOfBirth: "1976-03-01",
      startDate: "2014-04-03",
      street: "2737 Poe Lane",
      city: "Shawnee",
      state: "KS",
      zipCode: "66214",
      department: "Legal",
    },
    {
      id: 11,
      firstName: "Christina",
      lastName: "Leon",
      dateOfBirth: "1983-04-23",
      startDate: "2015-03-01",
      street: "3247 Hampton Meadows",
      city: "Haverhill",
      state: "MA",
      zipCode: "01830",
      department: "Sales",
    },
    {
      id: 12,
      firstName: "Richard",
      lastName: "Castillo",
      dateOfBirth: "1952-11-22",
      startDate: "2013-01-25",
      street: "4599 Hill Street",
      city: "Toledo",
      state: "OH",
      zipCode: "43609",
      department: "Marketing",
    },
    {
      id: 13,
      firstName: "Carl",
      lastName: "Sanders",
      dateOfBirth: "1953-10-20",
      startDate: "2015-11-02",
      street: "4225 Froe Street",
      city: "Wheeling",
      state: "WV",
      zipCode: "26003",
      department: "Engineering",
    },
    {
      id: 14,
      firstName: "Ethel",
      lastName: "Workman",
      dateOfBirth: "1988-06-20",
      startDate: "2014-03-17",
      street: "1622 Hummingbird Way",
      city: "Charlestown",
      state: "MA",
      zipCode: "02129",
      department: "Human Resources",
    },
    {
      id: 15,
      firstName: "John",
      lastName: "Roddy",
      dateOfBirth: "1976-03-01",
      startDate: "2014-04-03",
      street: "2737 Poe Lane",
      city: "Shawnee",
      state: "KS",
      zipCode: "66214",
      department: "Legal",
    },
  ],
};

const employeesSlice = createSlice({
  name: "employees",
  initialState: employeesState,
  reducers: {
    addEmployee: (state, action) => {
      state.list = [...state.list, action.payload];
    },
  },
});

export const { addEmployee } = employeesSlice.actions;

export const employeesReducer = employeesSlice.reducer;
